=head1 NAME

SU::API::Printfleet

=head1 SYNOPSIS

    use strict;
    use warnings;

    use SU::API::Printfleet;

    my $printfleet = SU::API::Printfleet->new({hostname => printfleet.example.com,
                                               username => $username,
                                               password => $password,
                                              });

    my $data = $printfleet->do_request($operation,{query => value});


=head1 DESCRIPTION

Module used to integrate with the REST API that Printfleet provides.

=head1 CONSTRUCTOR

=over

=item new ({hostname => $FQDN, username => $username, password => $password})

Returns a new SU::API::Printfleet object.

api_version => $version
Sets which version of Printfleet Rest API that is used. Defaults to 3.5.5

=back

=head1 METHODS

=over

=item do_request (OPERATION, DATA)

Perform the actual request.

"OPERATION" is which Printfleet method that is called.

"DATA" is a Perl data structure that will be converted to HTTP querys.

Returns the result in a perl reference.

=back

=head1 DEPENDS

L<HTTP::Request>,
L<JSON>,
L<LWP::UserAgent>,
L<String::Random>,
L<URI::Escape>
L<MIME::Base64>

=head1 LICENSE

Copyright (c) 2017-, IT Services, Stockholm University

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following
disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
disclaimer in the documentation and/or other materials provided with the distribution.

Neither the name of Stockholm University nor the names of its contributors may be used to endorse or promote products
derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=head1 AUTHOR

Björn Bohman <bjorn.bohman@su.se>

